@keycloakUrl=https://auth.unterrainer.info
@realm=safeLearn
@clientId=safeLearn
###
# @name POST OWN attributes (different URL) (needs no additional realm-management role)
POST {{keycloakUrl}}/realms/{{realm}}/account
Authorization: openid password env
Content-Type: application/json

{
  "firstName": "Tea",
  "lastName": "Cher",
  "email": "teacher@unterrainer.info",
  "attributes": {
    "config": "custom value2",
    "lastVisitedUrl": "https://safelearn.unterrainer.info"
  }
}

###
# @name GET OWN attributes (different URL) (needs no additional realm-management role)
GET {{keycloakUrl}}/realms/{{realm}}/account
Authorization: openid password env
Content-Type: application/json

###
