###
# @name POST OWN attributes (different URL) (needs no additional realm-management role)
POST {{keycloakUrl}}/realms/{{realm}}/account
Authorization: openid password env
Content-Type: application/json

{
  "attributes": {
    "firstName": "Tea",
    "lastName": "Cher",
    "config": "custom value1",
    "lastVisitedUrl": "https://safelearn.unterrainer.info"
  }
}

###
# @name GET OWN attributes (different URL) (needs no additional realm-management role)
GET {{keycloakUrl}}/realms/{{realm}}/account
Authorization: openid password env
Content-Type: application/json

###
