@endpoint=convert

###
# @name POST url
POST {{url}}/{{endpoint}}
Authorization: openid password env
Content-Type: application/json

{
  "url": "https://raw.githubusercontent.com/UnterrainerInformatik/cheatsheets/master/linux_cheat_sheet.md"
}

###
# @name POST contents
POST {{url}}/{{endpoint}}
Authorization: openid password env
Content-Type: application/json

{
  "content": "# TEST\n\nThis is a test file.\n\n## Subtitle\n\nThis is a subtitle.\n\n### Subsubtitle\n\nThis is a subsubtitle.\n\n#### Subsubsubtitle\n\nThis is a subsubsubtitle.\n\n##### Subsubsubsubtitle\n\nThis is a subsubsubsubtitle.\n\n###### Subsubsubsubsubtitle\n\nThis is a subsubsubsubsubtitle.\n\n####### Subsubsubsubsubsubtitle\n\nThis is a subsubsubsubsubsubtitle.\n\n######## Subsubsubsubsubsubsubtitle\n\nThis is a subsubsubsubsubsubsubtitle.\n\n######### Subsubsubsubsubsubsubsubtitle\n\nThis is a subsubsubsubsubsubsubsubtitle.\n\n########## Subsubsubsubsubsubsubsubsubtitle\n\nThis is a subsubsubsubsubsubsubsubsubtitle.\n\n########### Subsubsubsubsubsubsubsubsubsubtitle\n\nThis is a subsubsubsubsubsubsubsubsubsubtitle.\n\n############ Subsubsubsubsubsubsubsubsubsubsubtitle\n\nThis is a"
}

###