services:

  safeLearn:
    image: ${DOCKER_HUB_USER}/${DOCKER_IMAGE_NAME}:latest
    container_name: safeLearn
    restart: unless-stopped
    ports:
      - ${WEBSERVER_PORT}:${INTERNAL_PORT}
    environment:
      - NEXT_PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_START_PAGE=${PUBLIC_START_PAGE}
      - NEXT_AUTOSCAN=${AUTOSCAN}
    volumes:
      - ${LOCAL_DEV_MD_DIR}:/app/md
      - ./keycloak.json:/app/keycloak.json
